Repository twbs/blog, pull requests merged in 2021-01, with the labels that each got.

#179 Add blog post for Icons v1.3.0
  src/_posts/2021-01-06-bootstrap-icons-1-3-0.md
  src/_sass/_pygments-manni.scss
  src/_sass/_style.scss
  src/assets/img/2021/01/icons-130-new.png
Labels: release

#185 Add v4.6.0 post
  src/_posts/2021-01-19-bootstrap-icons-4.6.0.md
Labels: release, squash-me

#187 Fix v4.6.0 post name
  .github/workflows/ci.yml
  src/_posts/2021-01-19-bootstrap-4.6.0.md
Labels: enhancement
