Repository twbs/blog, pull requests merged in 2022-07, with the labels that each got.

#289 Update devDependencies
  package-lock.json
  package.json
Labels: dependencies

#290 Icons v190
  src/content/posts/2022/bootstrap-icons-1-9-0.md
  src/static/assets/img/2022/07/bootstrap-icons-v190.png
Labels: release

#293 Improve _markup/render-image.html
  src/layouts/_default/_markup/render-image.html
Labels: squash

#294 Improve banner partial
  src/layouts/partials/banner.html
Labels: squash

#291 Add v4.6.2 blog post
  src/content/posts/2022/bootstrap-4-6-2.md
Labels: release

#292 Add v5.2.0 post draft
  src/content/posts/2022/bootstrap-5-2-0.md
  src/static/assets/img/2022/07/bootstrap-guides@2x.png
  src/static/assets/img/2022/07/guides-stackblitz.png
  src/static/assets/img/2022/07/snippets-stackblitz.png
Labels: release, squash

#296 Update dependencies
  config.yml
  package-lock.json
  package.json
Labels: dependencies
