Repository twbs/blog, pull requests merged in 2023-03, with the labels that each got.

#351 Use a responsive image for bootstrap-logo-shadow.png
  build/vnu-jar.js
  src/layouts/partials/head.html
  src/layouts/partials/hero.html
  src/static/assets/brand/bootstrap-logo-shadow.png
  src/static/assets/brand/bootstrap-logo-shadow@2x.png
Labels: enhancement

#357 Add v5.3.0-alpha2 blog post
  src/content/posts/2023/bootstrap-5-3-0-alpha2.md
Labels: release, squash

#360 Update Bootstrap to v5.3.0-alpha2
  package-lock.json
  package.json
Labels: dependencies
