Repository twbs/blog, pull requests merged in 2024-03, with the labels that each got.

#422 Backport navbar rendering from upstream
  src/assets/scss/_navbar.scss
  src/layouts/partials/footer.html
  src/layouts/partials/icons/bootstrap-white-fill.svg
  src/layouts/partials/navbar.html
Labels: enhancement

#424 Fingerprint CSS and JS assets for cache busting
  hugo.yml
  src/layouts/partials/head.html
  src/layouts/partials/scripts.html
  src/layouts/partials/stylesheet.html
Labels: enhancement, squash

#432 Update dependencies
  package-lock.json
  package.json
Labels: dependencies

#445 Update dependencies
  package-lock.json
  package.json
Labels: dependencies
